export const dummyTasks = [
    {
        id: "1",
        header: "Fix login bug",
        status: "Pending",
        reviewer: "Alice Johnson",
        type: "Bug Fix",
        description: "Resolve the issue preventing users from logging in on mobile devices.",
    },
    {
        id: "2",
        header: "Update homepage banner",
        status: "In Review",
        reviewer: "Bob Smith",
        type: "Content Update",
        description: "Swap out the spring banner with the new summer campaign image.",
    },
    {
        id: "3",
        header: "Refactor payment module",
        status: "Completed",
        reviewer: "Charlie Nguyen",
        type: "Code Refactor",
        description: "Clean up and modularize payment handling logic for maintainability.",
    },
    {
        id: "4",
        header: "Add user onboarding tooltip",
        status: "Pending",
        reviewer: "Dana Lee",
        type: "Feature",
        description: "Create contextual tooltips for new users on the dashboard.",
    },
    {
        id: "5",
        header: "Correct FAQ typos",
        status: "Completed",
        reviewer: "Ethan Kim",
        type: "Content Update",
        description: "Fix grammatical errors and update outdated info in the FAQ.",
    },
    {
        id: "6",
        header: "Optimize images on product page",
        status: "In Progress",
        reviewer: "Fiona Patel",
        type: "Performance",
        description: "Compress and serve WebP images to improve load speed.",
    },
    {
        id: "7",
        header: "Fix signup redirect issue",
        status: "Pending",
        reviewer: "George Brown",
        type: "Bug Fix",
        description: "Users aren't redirected to the dashboard after signing up.",
    },
    {
        id: "8",
        header: "Implement dark mode toggle",
        status: "In Review",
        reviewer: "Hannah Davis",
        type: "Feature",
        description: "Allow users to toggle between light and dark themes.",
    },
    {
        id: "9",
        header: "Update pricing page layout",
        status: "Pending",
        reviewer: "Ivan Miller",
        type: "Design",
        description: "Redesign pricing tiers for better clarity and conversion.",
    },
    {
        id: "10",
        header: "Clean up console warnings",
        status: "Completed",
        reviewer: "Julia Roberts",
        type: "Code Cleanup",
        description: "Remove unused variables and deprecated lifecycle methods.",
    },
    {
        id: "11",
        header: "Improve accessibility labels",
        status: "In Progress",
        reviewer: "Kevin Zhang",
        type: "Accessibility",
        description: "Add ARIA labels to navigation and form inputs.",
    },
    {
        id: "12",
        header: "Add unit tests to auth module",
        status: "Pending",
        reviewer: "Laura Chen",
        type: "Testing",
        description: "Cover login and registration logic with unit tests.",
    },
    {
        id: "13",
        header: "Fix footer links",
        status: "Completed",
        reviewer: "Michael Scott",
        type: "Bug Fix",
        description: "Several links in the footer are broken or outdated.",
    },
    {
        id: "14",
        header: "Redesign user profile page",
        status: "In Review",
        reviewer: "Nina Garcia",
        type: "Design",
        description: "Give the profile page a modern layout and new typography.",
    },
    {
        id: "15",
        header: "Improve API error handling",
        status: "Pending",
        reviewer: "Oscar Wilde",
        type: "Backend",
        description: "Return clear and consistent error messages from all endpoints.",
    },
    {
        id: "16",
        header: "Create changelog page",
        status: "In Progress",
        reviewer: "Patricia Moore",
        type: "Feature",
        description: "Allow users to view the latest changes and release notes.",
    },
    {
        id: "17",
        header: "Fix navbar scroll bug",
        status: "Pending",
        reviewer: "Quentin Blake",
        type: "Bug Fix",
        description: "Navbar disappears when scrolling quickly on Safari.",
    },
    {
        id: "18",
        header: "Add forgot password flow",
        status: "Completed",
        reviewer: "Rachel Adams",
        type: "Feature",
        description: "Let users reset their password via email.",
    },
    {
        id: "19",
        header: "Update logo assets",
        status: "In Progress",
        reviewer: "Sam Carter",
        type: "Content Update",
        description: "Swap out old logos with new branding across the site.",
    },
    {
        id: "20",
        header: "Enable lazy loading on images",
        status: "In Review",
        reviewer: "Tina Fey",
        type: "Performance",
        description: "Improve load time by lazy loading off-screen images.",
    },
    {
        id: "21",
        header: "Convert app to TypeScript",
        status: "Pending",
        reviewer: "Uma Thurman",
        type: "Code Refactor",
        description: "Begin converting all JavaScript files to TypeScript.",
    },
]