
name: TaskGen CI

on:
  workflow_dispatch:

jobs:
  build:
    name: Manual CI Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run Linter
        run: pnpm lint

      - name: Build App
        run: pnpm build
